services:
  postgres:
    container_name: access-collect-postgres
    image: postgres:14-alpine
    ports:
      - 5556:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=tripluch
      - POSTGRES_USER=tripluch
      - POSTGRES_DB=test_db_access_collect
