name: Jest Tests
on:
  pull_request:
    branches: [main]

jobs:
  setup:
    runs-on: ubuntu-latest
    name: Setup Branch
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
           node-version: lts/*

      - name: Install dependencies for tests
        run: npm install

      - name: Test Jest
        run: npm run jest

