name: CI

on: push

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        # Install NPM dependencies, cache them correctly
        - run: npm install
        - run: npm run build

